repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

hooks:
  - id: black
    files: \\.py$
  - id: flake8
    files: \\.py$
  - id: ruff
    args: [--severity, error]
    files: \\.js$
  - id: bandit
    files: \\.py$
  - id: safety
    args: [--full-report]
    language: system
