repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.245'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
